logo = false
logoText = "L Chat"
logoType = "short"
description = "L Chat"
themeOptions = [ "light", "dark" ]
useFaviconGenerator = true
enableTocSwitch = true
enableLandingBackground = false
enableSearch = true
enableSearchHighlight = true
enableLangChange = true
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = false
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true
tocLevels = [ "h2", "h3", "h4" ]
paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006"
github = "https://github.com/zzossig/hugo-theme-zdoc"
enableComment = false
disqus_shortname = ""
commento = false

[gitment]
owner = ""
repo = ""
clientId = ""
clientSecret = ""

[utterances]
owner = ""
repo = ""

[gitalk]
owner = ""
repo = ""
clientId = ""
clientSecret = ""

[valine]
enable = false
appId = "你的appId"
appKey = "你的appKey"
notify = false
verify = false
avatar = "mm"
placeholder = "说点什么吧..."
visitor = false

[changyan]
changyanAppid = ""
changyanAppkey = ""

[livere]
livereUID = ""

[isso]
enable = false
scriptSrc = ""
dataAttrs = ""
